---
name: CI

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        uses: opdavies/github-action-workspace@v1
        with:
          args: install

      - name: Run phpcs
        uses: opdavies/github-action-workspace@v1
        with:
          args: test phpcs
